default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: medach_development
  port: 5431

test:
  <<: *default
  database: medach_test

production:
  <<: *default
  database: medach_production
  port: 5433
